### ISSUE TITLE
iOS port for SymSpell

### ISSUE THREAD

**Issue by AmitBhavsarIphone** [reneklacan/symspell#1]
Is it possible for you to make iOS port from Rust?

I try to create it but as I do not have knowledge of Rust I am not able to complete it.

If we can create this iOS port, we can help many needed iOS developers to use this great symspell library.

I can share you my demo project(iOS-Rust for SymSpell) with you.

https://drive.google.com/file/d/19vMeStYUWOZpEYtdybZMi_VZY9-EJmvG/view?usp=sharing 

Can you lease make required changes so we can use directly to iOS project?

**Comment by reneklacan** [comment]
I unfortunately don't have motivation or time to work on this but I'm more than happy to merge any PR adding FFI interface.
