### ISSUE TITLE
Python Bindings for Rust Crate?

### ISSUE THREAD

**Issue by VJAYSLN** [reneklacan/symspell#11]
Hello @reneklacan, you did a tremendous work on this !! I need some clarifications on this,
1) Is there any Python Bindings available for Rust Crate? And what is it?
2) Do you have any plan for providing such python bindings?

Thanks in Advance..)

**Comment by reneklacan** [comment]
Hey @VJAYSLN, looks like there's already a be pure python implementation of Symspell which is also quite maintained - https://github.com/mammothb/symspellpy

Or do you specifically wish for bindings to this crate?

I don't have any plans in providing python bindings but it should be reasonably easy for you to implement a new python package wrapping up this library using https://github.com/PyO3/pyo3

**Comment by VJAYSLN** [comment]
Hello @reneklacan, I'm Implemented a Python bindings for this package. Could I make a PR for that?
