### ISSUE TITLE
Use `triple_accel` instead of `strsim` to make it faster

### ISSUE THREAD

**Issue by mbartlett21** [reneklacan/symspell#23]
I would like a way to make this crate use triple_accel's Levenshtein distance instead of strsim's, since triple_accel's has an option to use simd, and set a maximum distance, rather than doing a full computation and discarding the result. This should make it quite a bit faster again.

[`levenshtein_simd_k_with_opts`](https://docs.rs/triple_accel/0.4.0/triple_accel/levenshtein/fn.levenshtein_simd_k_with_opts.html)

**Comment by reneklacan** [comment]
@mbartlett21 pull request is welcomed

**Comment by mbartlett21** [comment]
@reneklacan

Should I have it as a feature or just change it completely? It looks like triple_accel supports wasm, so it should work just like that

**Comment by reneklacan** [comment]
@mbartlett21 I'm fine with replacing it completely as long as you make sure it's providing the same results as the previous implementation (for reasonable max distance) and as long as you benchmark it and it's really faster.
